#pragma once
#include "Exports.hpp"
#define WinHTTP_IMPL_FUNCTION_LIST \
    DECLARE_IMPL_NAME(ImplSvchostPushServiceGlobals) \
    DECLARE_IMPL_NAME(ImplWinHttpAddRequestHeaders) \
    DECLARE_IMPL_NAME(ImplWinHttpAddRequestHeadersEx) \
    DECLARE_IMPL_NAME(ImplWinHttpAutoProxySvcMain) \
    DECLARE_IMPL_NAME(ImplWinHttpCheckPlatform) \
    DECLARE_IMPL_NAME(ImplWinHttpCloseHandle) \
    DECLARE_IMPL_NAME(ImplWinHttpConnect) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionDeletePolicyEntries) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionDeleteProxyInfo) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionFreeNameList) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionFreeProxyInfo) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionFreeProxyList) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionGetNameList) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionGetProxyInfo) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionGetProxyList) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionOnlyConvert) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionOnlyReceive) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionOnlySend) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionSetPolicyEntries) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionSetProxyInfo) \
    DECLARE_IMPL_NAME(ImplWinHttpConnectionUpdateIfIndexTable) \
    DECLARE_IMPL_NAME(ImplWinHttpCrackUrl) \
    DECLARE_IMPL_NAME(ImplWinHttpCreateProxyList) \
    DECLARE_IMPL_NAME(ImplWinHttpCreateProxyManager) \
    DECLARE_IMPL_NAME(ImplWinHttpCreateProxyResolver) \
    DECLARE_IMPL_NAME(ImplWinHttpCreateProxyResult) \
    DECLARE_IMPL_NAME(ImplWinHttpCreateUiCompatibleProxyString) \
    DECLARE_IMPL_NAME(ImplWinHttpCreateUrl) \
    DECLARE_IMPL_NAME(ImplWinHttpDetectAutoProxyConfigUrl) \
    DECLARE_IMPL_NAME(ImplWinHttpFreeProxyResult) \
    DECLARE_IMPL_NAME(ImplWinHttpFreeProxyResultEx) \
    DECLARE_IMPL_NAME(ImplWinHttpFreeProxySettings) \
    DECLARE_IMPL_NAME(ImplWinHttpFreeProxySettingsEx) \
    DECLARE_IMPL_NAME(ImplWinHttpFreeQueryConnectionGroupResult) \
    DECLARE_IMPL_NAME(ImplWinHttpGetDefaultProxyConfiguration) \
    DECLARE_IMPL_NAME(ImplWinHttpGetIEProxyConfigForCurrentUser) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxyForUrl) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxyForUrlEx) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxyForUrlEx2) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxyForUrlHvsi) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxyResult) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxyResultEx) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxySettingsEx) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxySettingsResultEx) \
    DECLARE_IMPL_NAME(ImplWinHttpGetProxySettingsVersion) \
    DECLARE_IMPL_NAME(ImplWinHttpGetTunnelSocket) \
    DECLARE_IMPL_NAME(ImplWinHttpOpen) \
    DECLARE_IMPL_NAME(ImplWinHttpOpenRequest) \
    DECLARE_IMPL_NAME(ImplWinHttpPacJsWorkerMain) \
    DECLARE_IMPL_NAME(ImplWinHttpProbeConnectivity) \
    DECLARE_IMPL_NAME(ImplWinHttpProtocolCompleteUpgrade) \
    DECLARE_IMPL_NAME(ImplWinHttpProtocolReceive) \
    DECLARE_IMPL_NAME(ImplWinHttpProtocolSend) \
    DECLARE_IMPL_NAME(ImplWinHttpQueryAuthSchemes) \
    DECLARE_IMPL_NAME(ImplWinHttpQueryConnectionGroup) \
    DECLARE_IMPL_NAME(ImplWinHttpQueryDataAvailable) \
    DECLARE_IMPL_NAME(ImplWinHttpQueryHeaders) \
    DECLARE_IMPL_NAME(ImplWinHttpQueryHeadersEx) \
    DECLARE_IMPL_NAME(ImplWinHttpQueryOption) \
    DECLARE_IMPL_NAME(ImplWinHttpReadData) \
    DECLARE_IMPL_NAME(ImplWinHttpReadDataEx) \
    DECLARE_IMPL_NAME(ImplWinHttpReadProxySettings) \
    DECLARE_IMPL_NAME(ImplWinHttpReadProxySettingsHvsi) \
    DECLARE_IMPL_NAME(ImplWinHttpReceiveResponse) \
    DECLARE_IMPL_NAME(ImplWinHttpRefreshProxySettings) \
    DECLARE_IMPL_NAME(ImplWinHttpRegisterProxyChangeNotification) \
    DECLARE_IMPL_NAME(ImplWinHttpResetAutoProxy) \
    DECLARE_IMPL_NAME(ImplWinHttpResolverGetProxyForUrl) \
    DECLARE_IMPL_NAME(ImplWinHttpSaveProxyCredentials) \
    DECLARE_IMPL_NAME(ImplWinHttpSendRequest) \
    DECLARE_IMPL_NAME(ImplWinHttpSetCredentials) \
    DECLARE_IMPL_NAME(ImplWinHttpSetDefaultProxyConfiguration) \
    DECLARE_IMPL_NAME(ImplWinHttpSetOption) \
    DECLARE_IMPL_NAME(ImplWinHttpSetProxySettingsPerUser) \
    DECLARE_IMPL_NAME(ImplWinHttpSetSecureLegacyServersAppCompat) \
    DECLARE_IMPL_NAME(ImplWinHttpSetStatusCallback) \
    DECLARE_IMPL_NAME(ImplWinHttpSetTimeouts) \
    DECLARE_IMPL_NAME(ImplWinHttpTimeFromSystemTime) \
    DECLARE_IMPL_NAME(ImplWinHttpTimeToSystemTime) \
    DECLARE_IMPL_NAME(ImplWinHttpUnregisterProxyChangeNotification) \
    DECLARE_IMPL_NAME(ImplWinHttpWebSocketClose) \
    DECLARE_IMPL_NAME(ImplWinHttpWebSocketCompleteUpgrade) \
    DECLARE_IMPL_NAME(ImplWinHttpWebSocketQueryCloseStatus) \
    DECLARE_IMPL_NAME(ImplWinHttpWebSocketReceive) \
    DECLARE_IMPL_NAME(ImplWinHttpWebSocketSend) \
    DECLARE_IMPL_NAME(ImplWinHttpWebSocketShutdown) \
    DECLARE_IMPL_NAME(ImplWinHttpWriteData) \
    DECLARE_IMPL_NAME(ImplWinHttpWriteProxySettings) \

namespace WinHTTPExports {
    constexpr std::array<std::string_view, 88> GetAllImplNames() {
        return { WinHTTP_IMPL_FUNCTION_LIST };
    }
}