#pragma once
#include "Exports.hpp"
#define WinMM_IMPL_FUNCTION_LIST \
    DECLARE_IMPL_NAME(ImplCloseDriver) \
    DECLARE_IMPL_NAME(ImplDefDriverProc) \
    DECLARE_IMPL_NAME(ImplDriverCallback) \
    DECLARE_IMPL_NAME(ImplDrvGetModuleHandle) \
    DECLARE_IMPL_NAME(ImplGetDriverModuleHandle) \
    DECLARE_IMPL_NAME(ImplOpenDriver) \
    DECLARE_IMPL_NAME(ImplPlaySound) \
    DECLARE_IMPL_NAME(ImplPlaySoundA) \
    DECLARE_IMPL_NAME(ImplPlaySoundW) \
    DECLARE_IMPL_NAME(ImplSendDriverMessage) \
    DECLARE_IMPL_NAME(ImplWOWAppExit) \
    DECLARE_IMPL_NAME(ImplauxGetDevCapsA) \
    DECLARE_IMPL_NAME(ImplauxGetDevCapsW) \
    DECLARE_IMPL_NAME(ImplauxGetNumDevs) \
    DECLARE_IMPL_NAME(ImplauxGetVolume) \
    DECLARE_IMPL_NAME(ImplauxOutMessage) \
    DECLARE_IMPL_NAME(ImplauxSetVolume) \
    DECLARE_IMPL_NAME(ImpljoyConfigChanged) \
    DECLARE_IMPL_NAME(ImpljoyGetDevCapsA) \
    DECLARE_IMPL_NAME(ImpljoyGetDevCapsW) \
    DECLARE_IMPL_NAME(ImpljoyGetNumDevs) \
    DECLARE_IMPL_NAME(ImpljoyGetPos) \
    DECLARE_IMPL_NAME(ImpljoyGetPosEx) \
    DECLARE_IMPL_NAME(ImpljoyGetThreshold) \
    DECLARE_IMPL_NAME(ImpljoyReleaseCapture) \
    DECLARE_IMPL_NAME(ImpljoySetCapture) \
    DECLARE_IMPL_NAME(ImpljoySetThreshold) \
    DECLARE_IMPL_NAME(ImplmciDriverNotify) \
    DECLARE_IMPL_NAME(ImplmciDriverYield) \
    DECLARE_IMPL_NAME(ImplmciExecute) \
    DECLARE_IMPL_NAME(ImplmciFreeCommandResource) \
    DECLARE_IMPL_NAME(ImplmciGetCreatorTask) \
    DECLARE_IMPL_NAME(ImplmciGetDeviceIDA) \
    DECLARE_IMPL_NAME(ImplmciGetDeviceIDFromElementIDA) \
    DECLARE_IMPL_NAME(ImplmciGetDeviceIDFromElementIDW) \
    DECLARE_IMPL_NAME(ImplmciGetDeviceIDW) \
    DECLARE_IMPL_NAME(ImplmciGetDriverData) \
    DECLARE_IMPL_NAME(ImplmciGetErrorStringA) \
    DECLARE_IMPL_NAME(ImplmciGetErrorStringW) \
    DECLARE_IMPL_NAME(ImplmciGetYieldProc) \
    DECLARE_IMPL_NAME(ImplmciLoadCommandResource) \
    DECLARE_IMPL_NAME(ImplmciSendCommandA) \
    DECLARE_IMPL_NAME(ImplmciSendCommandW) \
    DECLARE_IMPL_NAME(ImplmciSendStringA) \
    DECLARE_IMPL_NAME(ImplmciSendStringW) \
    DECLARE_IMPL_NAME(ImplmciSetDriverData) \
    DECLARE_IMPL_NAME(ImplmciSetYieldProc) \
    DECLARE_IMPL_NAME(ImplmidiConnect) \
    DECLARE_IMPL_NAME(ImplmidiDisconnect) \
    DECLARE_IMPL_NAME(ImplmidiInAddBuffer) \
    DECLARE_IMPL_NAME(ImplmidiInClose) \
    DECLARE_IMPL_NAME(ImplmidiInGetDevCapsA) \
    DECLARE_IMPL_NAME(ImplmidiInGetDevCapsW) \
    DECLARE_IMPL_NAME(ImplmidiInGetErrorTextA) \
    DECLARE_IMPL_NAME(ImplmidiInGetErrorTextW) \
    DECLARE_IMPL_NAME(ImplmidiInGetID) \
    DECLARE_IMPL_NAME(ImplmidiInGetNumDevs) \
    DECLARE_IMPL_NAME(ImplmidiInMessage) \
    DECLARE_IMPL_NAME(ImplmidiInOpen) \
    DECLARE_IMPL_NAME(ImplmidiInPrepareHeader) \
    DECLARE_IMPL_NAME(ImplmidiInReset) \
    DECLARE_IMPL_NAME(ImplmidiInStart) \
    DECLARE_IMPL_NAME(ImplmidiInStop) \
    DECLARE_IMPL_NAME(ImplmidiInUnprepareHeader) \
    DECLARE_IMPL_NAME(ImplmidiOutCacheDrumPatches) \
    DECLARE_IMPL_NAME(ImplmidiOutCachePatches) \
    DECLARE_IMPL_NAME(ImplmidiOutClose) \
    DECLARE_IMPL_NAME(ImplmidiOutGetDevCapsA) \
    DECLARE_IMPL_NAME(ImplmidiOutGetDevCapsW) \
    DECLARE_IMPL_NAME(ImplmidiOutGetErrorTextA) \
    DECLARE_IMPL_NAME(ImplmidiOutGetErrorTextW) \
    DECLARE_IMPL_NAME(ImplmidiOutGetID) \
    DECLARE_IMPL_NAME(ImplmidiOutGetNumDevs) \
    DECLARE_IMPL_NAME(ImplmidiOutGetVolume) \
    DECLARE_IMPL_NAME(ImplmidiOutLongMsg) \
    DECLARE_IMPL_NAME(ImplmidiOutMessage) \
    DECLARE_IMPL_NAME(ImplmidiOutOpen) \
    DECLARE_IMPL_NAME(ImplmidiOutPrepareHeader) \
    DECLARE_IMPL_NAME(ImplmidiOutReset) \
    DECLARE_IMPL_NAME(ImplmidiOutSetVolume) \
    DECLARE_IMPL_NAME(ImplmidiOutShortMsg) \
    DECLARE_IMPL_NAME(ImplmidiOutUnprepareHeader) \
    DECLARE_IMPL_NAME(ImplmidiStreamClose) \
    DECLARE_IMPL_NAME(ImplmidiStreamOpen) \
    DECLARE_IMPL_NAME(ImplmidiStreamOut) \
    DECLARE_IMPL_NAME(ImplmidiStreamPause) \
    DECLARE_IMPL_NAME(ImplmidiStreamPosition) \
    DECLARE_IMPL_NAME(ImplmidiStreamProperty) \
    DECLARE_IMPL_NAME(ImplmidiStreamRestart) \
    DECLARE_IMPL_NAME(ImplmidiStreamStop) \
    DECLARE_IMPL_NAME(ImplmixerClose) \
    DECLARE_IMPL_NAME(ImplmixerGetControlDetailsA) \
    DECLARE_IMPL_NAME(ImplmixerGetControlDetailsW) \
    DECLARE_IMPL_NAME(ImplmixerGetDevCapsA) \
    DECLARE_IMPL_NAME(ImplmixerGetDevCapsW) \
    DECLARE_IMPL_NAME(ImplmixerGetID) \
    DECLARE_IMPL_NAME(ImplmixerGetLineControlsA) \
    DECLARE_IMPL_NAME(ImplmixerGetLineControlsW) \
    DECLARE_IMPL_NAME(ImplmixerGetLineInfoA) \
    DECLARE_IMPL_NAME(ImplmixerGetLineInfoW) \
    DECLARE_IMPL_NAME(ImplmixerGetNumDevs) \
    DECLARE_IMPL_NAME(ImplmixerMessage) \
    DECLARE_IMPL_NAME(ImplmixerOpen) \
    DECLARE_IMPL_NAME(ImplmixerSetControlDetails) \
    DECLARE_IMPL_NAME(ImplmmDrvInstall) \
    DECLARE_IMPL_NAME(ImplmmGetCurrentTask) \
    DECLARE_IMPL_NAME(ImplmmTaskBlock) \
    DECLARE_IMPL_NAME(ImplmmTaskCreate) \
    DECLARE_IMPL_NAME(ImplmmTaskSignal) \
    DECLARE_IMPL_NAME(ImplmmTaskYield) \
    DECLARE_IMPL_NAME(ImplmmioAdvance) \
    DECLARE_IMPL_NAME(ImplmmioAscend) \
    DECLARE_IMPL_NAME(ImplmmioClose) \
    DECLARE_IMPL_NAME(ImplmmioCreateChunk) \
    DECLARE_IMPL_NAME(ImplmmioDescend) \
    DECLARE_IMPL_NAME(ImplmmioFlush) \
    DECLARE_IMPL_NAME(ImplmmioGetInfo) \
    DECLARE_IMPL_NAME(ImplmmioInstallIOProcA) \
    DECLARE_IMPL_NAME(ImplmmioInstallIOProcW) \
    DECLARE_IMPL_NAME(ImplmmioOpenA) \
    DECLARE_IMPL_NAME(ImplmmioOpenW) \
    DECLARE_IMPL_NAME(ImplmmioRead) \
    DECLARE_IMPL_NAME(ImplmmioRenameA) \
    DECLARE_IMPL_NAME(ImplmmioRenameW) \
    DECLARE_IMPL_NAME(ImplmmioSeek) \
    DECLARE_IMPL_NAME(ImplmmioSendMessage) \
    DECLARE_IMPL_NAME(ImplmmioSetBuffer) \
    DECLARE_IMPL_NAME(ImplmmioSetInfo) \
    DECLARE_IMPL_NAME(ImplmmioStringToFOURCCA) \
    DECLARE_IMPL_NAME(ImplmmioStringToFOURCCW) \
    DECLARE_IMPL_NAME(ImplmmioWrite) \
    DECLARE_IMPL_NAME(ImplmmsystemGetVersion) \
    DECLARE_IMPL_NAME(ImplsndPlaySoundA) \
    DECLARE_IMPL_NAME(ImplsndPlaySoundW) \
    DECLARE_IMPL_NAME(ImpltimeBeginPeriod) \
    DECLARE_IMPL_NAME(ImpltimeEndPeriod) \
    DECLARE_IMPL_NAME(ImpltimeGetDevCaps) \
    DECLARE_IMPL_NAME(ImpltimeGetSystemTime) \
    DECLARE_IMPL_NAME(ImpltimeGetTime) \
    DECLARE_IMPL_NAME(ImpltimeKillEvent) \
    DECLARE_IMPL_NAME(ImpltimeSetEvent) \
    DECLARE_IMPL_NAME(ImplwaveInAddBuffer) \
    DECLARE_IMPL_NAME(ImplwaveInClose) \
    DECLARE_IMPL_NAME(ImplwaveInGetDevCapsA) \
    DECLARE_IMPL_NAME(ImplwaveInGetDevCapsW) \
    DECLARE_IMPL_NAME(ImplwaveInGetErrorTextA) \
    DECLARE_IMPL_NAME(ImplwaveInGetErrorTextW) \
    DECLARE_IMPL_NAME(ImplwaveInGetID) \
    DECLARE_IMPL_NAME(ImplwaveInGetNumDevs) \
    DECLARE_IMPL_NAME(ImplwaveInGetPosition) \
    DECLARE_IMPL_NAME(ImplwaveInMessage) \
    DECLARE_IMPL_NAME(ImplwaveInOpen) \
    DECLARE_IMPL_NAME(ImplwaveInPrepareHeader) \
    DECLARE_IMPL_NAME(ImplwaveInReset) \
    DECLARE_IMPL_NAME(ImplwaveInStart) \
    DECLARE_IMPL_NAME(ImplwaveInStop) \
    DECLARE_IMPL_NAME(ImplwaveInUnprepareHeader) \
    DECLARE_IMPL_NAME(ImplwaveOutBreakLoop) \
    DECLARE_IMPL_NAME(ImplwaveOutClose) \
    DECLARE_IMPL_NAME(ImplwaveOutGetDevCapsA) \
    DECLARE_IMPL_NAME(ImplwaveOutGetDevCapsW) \
    DECLARE_IMPL_NAME(ImplwaveOutGetErrorTextA) \
    DECLARE_IMPL_NAME(ImplwaveOutGetErrorTextW) \
    DECLARE_IMPL_NAME(ImplwaveOutGetID) \
    DECLARE_IMPL_NAME(ImplwaveOutGetNumDevs) \
    DECLARE_IMPL_NAME(ImplwaveOutGetPitch) \
    DECLARE_IMPL_NAME(ImplwaveOutGetPlaybackRate) \
    DECLARE_IMPL_NAME(ImplwaveOutGetPosition) \
    DECLARE_IMPL_NAME(ImplwaveOutGetVolume) \
    DECLARE_IMPL_NAME(ImplwaveOutMessage) \
    DECLARE_IMPL_NAME(ImplwaveOutOpen) \
    DECLARE_IMPL_NAME(ImplwaveOutPause) \
    DECLARE_IMPL_NAME(ImplwaveOutPrepareHeader) \
    DECLARE_IMPL_NAME(ImplwaveOutReset) \
    DECLARE_IMPL_NAME(ImplwaveOutRestart) \
    DECLARE_IMPL_NAME(ImplwaveOutSetPitch) \
    DECLARE_IMPL_NAME(ImplwaveOutSetPlaybackRate) \
    DECLARE_IMPL_NAME(ImplwaveOutSetVolume) \
    DECLARE_IMPL_NAME(ImplwaveOutUnprepareHeader) \
    DECLARE_IMPL_NAME(ImplwaveOutWrite) \

namespace WinMMExports {
    constexpr std::array<std::string_view, 180> GetAllImplNames() {
        return { WinMM_IMPL_FUNCTION_LIST };
    }
}